name: daprme formula on tag

on:
  push:
    tags:
      - 'v*' # v0.8.1

jobs:

  build:
    name: Formula
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 1

      - name: Commit
        run: |
          sudo apt-get install -y jq

      - name: Set env
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/*/}
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: SHA
        run: |
          echo "daprme tag: ${RELEASE_TAG}"
          ASSET_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/dapr-templates/daprme/releases/tags/${RELEASE_TAG}" | jq '.assets[] | select(.name=="daprme") | .url')
          ASSET_SHA=$(curl -L -f -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $ASSET_URL 2> \
            /dev/null | shasum -a 256 | sed -n 's/\(.*\) -/\1/p' | xargs -I {} echo {} )
          echo "ASSET_SHA=${ASSET_SHA}" >> $GITHUB_ENV

      - name: Formula
        run: |
          sed -e "s/TAGVALUE/${RELEASE_TAG}/g" -e "s/SHAVALUE/${ASSET_SHA}/g" daprme.tmpl > daprme-test.rb

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daprme.rb
          git commit -m "formula ${RELEASE_TAG}"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          